CREATE TABLE lines (
  id SERIAL PRIMARY KEY
);

CREATE TABLE points (
  id SERIAL PRIMARY KEY,
  line_id INTEGER REFERENCES lines(id),
  x DOUBLE PRECISION,
  y DOUBLE PRECISION
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  x DOUBLE PRECISION,
  y DOUBLE PRECISION,
  width DOUBLE PRECISION,
  height DOUBLE PRECISION,
  image_url TEXT
);

CREATE TABLE text_boxes (
  id SERIAL PRIMARY KEY,
  x DOUBLE PRECISION,
  y DOUBLE PRECISION,
  width DOUBLE PRECISION,
  height DOUBLE PRECISION,
  content TEXT
);
